spring.application.name=demo
spring.security.oauth2.client.registration.github.client-name=Meu aplicativo Java
spring.security.oauth2.client.registration.github.client-id=id
spring.security.oauth2.client.registration.github.client-secret=segredo
spring.security.oauth2.client.registration.github.scope=user,repo
