spring.application.name=demo
spring.security.oauth2.client.registration.github.client-name=Meu aplicativo Java
spring.security.oauth2.client.registration.github.client-id=Ov23liysNreHOaOXqLtV
spring.security.oauth2.client.registration.github.client-secret=50daf80a0f55172c91fe0814aadc15fe0b05cb69
spring.security.oauth2.client.registration.github.scope=user,repo